#!/usr/bin/env bash
# Runs the Luau test suite against the plugin sources, unmodified.
#
# The Luau CLI has no file I/O, so the plugin's .luau sources, the fixtures and
# translations/en.json are embedded into tests/_generated/sources.luau first;
# tests/support/loader.luau then loads them in a sandbox with a fake `noctalia`
# host and Noctalia's require("./x.luau") semantics.
#
# Usage: scripts/test.sh            (fetches the Luau CLI into .tools/ if missing)
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"

luau="${LUAU:-}"
if [[ -z "$luau" ]]; then
  if command -v luau >/dev/null 2>&1; then
    luau="$(command -v luau)"
  else
    luau="$root/.tools/luau"
    if [[ ! -x "$luau" ]]; then
      echo "Fetching the Luau CLI into .tools/ …" >&2
      mkdir -p .tools
      curl -fsSL -o .tools/luau.zip https://github.com/luau-lang/luau/releases/latest/download/luau-ubuntu.zip
      unzip -oq .tools/luau.zip -d .tools && rm .tools/luau.zip
    fi
  fi
fi

python3 - <<'PY'
import pathlib, re
root = pathlib.Path(".")
files = [p for p in root.rglob("*.luau") if not p.parts[0] in ("tests", ".tools")]
files += list(root.glob("providers/*/*.svg")) + list(root.glob("tests/fixtures/*.json")) + [root / "translations/en.json", root / "plugin.toml"]

def quote(text):
    level = 0
    while ("]" + "=" * level + "]") in text:
        level += 1
    eq = "=" * level
    return f"[{eq}[\n{text}]{eq}]"

out = ["-- Generated by scripts/test.sh. Do not edit.", "return {"]
for path in sorted(files):
    out.append(f'  ["{path.as_posix()}"] = {quote(path.read_text())},')
out.append("}")
gen = root / "tests/_generated"
gen.mkdir(exist_ok=True)
(gen / "sources.luau").write_text("\n".join(out) + "\n")
PY

exec "$luau" tests/run.luau
